[project]
name = "updater"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Morgan Gangwere", email = "morgan.gangwere@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
updater = "updater:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
